//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITEC
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public group()
        {
            this.users = new HashSet<user>();
            this.users1 = new HashSet<user>();
        }
    
        public int gr_id { get; set; }
        public string name { get; set; }
        public string descr { get; set; }
    
        public virtual ICollection<user> users { get; set; }
        public virtual ICollection<user> users1 { get; set; }
    }
}
