//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITEC
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int item_id { get; set; }
        public string name { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> points { get; set; }
    
        public virtual category category { get; set; }
    }
}
