//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITEC
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.groups = new HashSet<group>();
            this.groups1 = new HashSet<group>();
        }
    
        public int usr_id { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> reg_data { get; set; }
        public string welcome_msg { get; set; }
        public Nullable<int> no_points { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<group> groups { get; set; }
        public virtual ICollection<group> groups1 { get; set; }
    }
}
